# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.7.2'

gem 'dry-system'
gem "hanami-api"
gem 'thin'

gem 'rom'
gem 'rom-sql'
gem 'rom-repository'
gem 'pg'

gem 'dotenv'
gem 'rake'

gem 'dry-struct'
gem 'dry-monads'

gem 'waterdrop'

group :development do
  gem 'ruby_jard'
end
